<?php 

return
[
	
	'BTREEENVIRONMENT'=> env('BTREE_ENVIRONMENT'),
	'BTREEMERCHANTID' => env('BTREE_MERCHANT_ID'),
	'BTREEPUBLICKEY' => env('BTREE_PUBLIC_KEY'),
	'BTREEPRIVATEKEY' => env('BTREE_PRIVATE_KEY'),
	'BTREEMERCHANTACCOUNTID' => env('BTREE_MERCHANT_ACCOUNT_ID')

];